<?php

/*
 * Editor server script for DB table EVENTS
 * Automatically generated by http://editor.datatables.net/generator
 */

// DataTables PHP library
include( "lib/DataTables.php" );

// Alias Editor classes so they are easy to use
use
	DataTables\Editor,
	DataTables\Editor\Field,
	DataTables\Editor\Format,
	DataTables\Editor\Join,
	DataTables\Editor\Validate;


// Build our Editor instance and process the data coming from _POST
Editor::inst( $db, 'DISPLAYS' )
	->fields(
		Field::inst( 'DISP_NAME' )
			->validator( 'Validate::required' ),
		Field::inst( 'DISP_ROOM_COUNT' )
			->validator( 'Validate::required' ),
		Field::inst( 'DISP_ROOM_1' )
			->validator( 'Validate::required' ),
		Field::inst( 'DISP_ROOM_1_SIDE' )
			->validator( 'Validate::required' ),
		Field::inst( 'DISP_ROOM_2' )
			->validator( 'Validate::required' ),
		Field::inst( 'DISP_ROOM_2_SIDE' )
			->validator( 'Validate::required' )
	)
	->process( $_POST )
	->json();

