<?php

/*
 * Editor server script for DB table EVENTS
 * Automatically generated by http://editor.datatables.net/generator
 */

// DataTables PHP library
include( "lib/DataTables.php" );

// Alias Editor classes so they are easy to use
use
	DataTables\Editor,
	DataTables\Editor\Field,
	DataTables\Editor\Format,
	DataTables\Editor\Join,
	DataTables\Editor\Validate;


// Build our Editor instance and process the data coming from _POST
Editor::inst( $db, 'EVENTS' )
	->fields(
		Field::inst( 'EVENT_TITLE' )
			->validator( 'Validate::maxLen_required', 30 ),
		Field::inst( 'EVENT_SUBTITLE' )
			->validator( 'Validate::maxLen_required', 30 ),
		Field::inst( 'EVENT_START' )
			->validator( 'Validate::required' ),
		Field::inst( 'EVENT_END' )
			->validator( 'Validate::required' ),
		Field::inst( 'EVENT_TRAINER' )
			->validator( 'Validate::required' ),
		Field::inst( 'EVENT_ROOM' )
			->validator( 'Validate::required' ),
		Field::inst( 'EVENT_TYPE_1' )
			->validator( 'Validate::required' ),
		Field::inst( 'EVENT_TYPE_2' )
			->validator( 'Validate::required' ),
		Field::inst( 'CREATE_USER' )
			->validator( 'Validate::required' )
	)
	->process( $_POST )
	->json();

